
from django.urls import path
from.views import (
    AdminPaymentListView, AdminProfileListView, AdminSubscriptionPlanDetailView,
    AdminSubscriptionPlanListCreateView, AdminSubscriptionPlanView,
    AdminSuccessStoryDetailView, AdminSuccessStoryListCreateView, AdvertisementView, CreateRazorpayOrderView,
    FavouriteProfileView, MyFavouriteView, MyLikesView, MyMatchesView,
    RegisterView, LoginView, GetUserView, RemoveFavouriteView, UnlikeProfileView,
    UpdateProfileTypeView, SendOTPView, VerifyOTPView,
    ResetPasswordView, UpdateBasicDetailsView,
    UpdateReligionView, UpdateEducationView, AdminDashboardStatsView,
    AdminRecentRegistrationsView, AdminProfileView,
    UpdateLocationView, UpdatePersonalDetailsView, ProfileDetailsView, LikeProfileView,
    AllProfilesListView, UpdateProfileView, BlockUserView, UserPreferencesView, NotificationSettingView, UserSubscriptionView,
    AdminUsersView, AdminUserDetailView, AdminProfilesView, AdminVerifyProfileView,
    AadhaarVerificationView, AdminPaymentDetailsView, ProcessPlanPurchaseView, VerifyPaymentView,
    add_comment, chat_request_action, delete_messages_view, get_notifications,
    get_public_plans, get_success_stories_public, mark_notification_read, get_admin_user, get_admin_profile,
    report_problem_api, send_image_message, send_support_message_api, update_admin_profile,
    get_chat_rooms, create_or_get_chat, get_messages, send_message, send_voice_message,
    change_password
)
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('login/', LoginView.as_view()),
    path('register/', RegisterView.as_view()),
    path('user/', GetUserView.as_view()),
    path('token/refresh/', TokenRefreshView.as_view()),
    path('profile/', UpdateProfileView.as_view(), name='profile'),
    path('profile/update-type/', UpdateProfileTypeView.as_view(), name='update_profile_type'),
    path('profile/basic-details/', UpdateBasicDetailsView.as_view()),
    path('profile/religion/', UpdateReligionView.as_view()),
    path('profile/education/', UpdateEducationView.as_view()),
    path('profile/location/', UpdateLocationView.as_view()),
    path('profile/personal-details/', UpdatePersonalDetailsView.as_view()),
    path("profile/<int:id>/", ProfileDetailsView.as_view(), name="profile_details"),
    path('forgot-password/send-otp/', SendOTPView.as_view()),
    path('forgot-password/verify-otp/', VerifyOTPView.as_view()),
    path('forgot-password/reset/', ResetPasswordView.as_view()),
    path("like-profile/", LikeProfileView.as_view(), name="like_profile"),
    path("unlike-profile/<int:profile_id>/", UnlikeProfileView.as_view()),
    path("favourite-profile/", FavouriteProfileView.as_view()),
    path("remove-favourite/<int:profile_id>/", RemoveFavouriteView.as_view()),
    path("my-likes/", MyLikesView.as_view()),
    path("my-favourites/", MyFavouriteView.as_view()),
    path('profiles/', AllProfilesListView.as_view()),
    path('ads/', AdvertisementView.as_view()),
    path('admin/ads/', AdvertisementView.as_view(), name='admin-ads'),
    path('admin/ads/<int:pk>/', AdvertisementView.as_view(), name='admin-ad-detail'),
    path('block-user/', BlockUserView.as_view(), name='block_user'),
    path('preferences/', UserPreferencesView.as_view(), name='user_preferences'),
    path('support/', send_support_message_api, name='support_message'),
    path('notifications/', NotificationSettingView.as_view(), name='notification_settings'),
    path('subscription/', UserSubscriptionView.as_view(), name='user_subscription'),
    path('report-problem/', report_problem_api, name='report_problem'),
    path('user-notifications/', get_notifications, name='get_notifications'),
    path('notifications/<int:notification_id>/read/', mark_notification_read, name='mark_notification_read'),
    path('add-comment/', add_comment, name='add_comment'),
    path('chat-rooms/', get_chat_rooms, name='get_chat_rooms'),
    path('chat/create/', create_or_get_chat, name='create_chat'),
    path('chat/<int:room_id>/messages/', get_messages, name='get_messages'),
    path('chat/send-message/', send_message, name='send_message'),
    path('change-password/', change_password, name='change_password'),
    path('chat/send-voice/', send_voice_message, name='send-voice'),
    path('chat/send-image/', send_image_message, name='send_image_message'),
    path('chat/request-action/<int:room_id>/', chat_request_action, name='chat_request_action'),
    path('chat/delete-message/', delete_messages_view, name='delete_messages_view'),
    path('admin/stats/', AdminDashboardStatsView.as_view(), name='admin-stats'),
    path('admin/recent-registrations/', AdminRecentRegistrationsView.as_view(), name='admin-recent-registrations'),
    path('admin/users/', AdminUsersView.as_view(), name='admin-users'),
    path('admin/users/<int:user_id>/', AdminUserDetailView.as_view(), name='admin-user-detail'),
    path('admin/profiles/', AdminProfileListView.as_view()),
    path('admin/profiles/<int:profile_id>/verify/', AdminVerifyProfileView.as_view(), name='admin-verify-profile'),
    path("admin-user/", get_admin_user, name="admin-user"),
    path('admin/profile/', get_admin_profile, name='get_admin_profile'),
    path('admin/profile/update/', update_admin_profile, name='update_admin_profile'),
    path('aadhaar-verification/', AadhaarVerificationView.as_view(), name='aadhaar-verification'),
    path("my-matches/", MyMatchesView.as_view(), name="my_matches"),
    path('admin/stories/', AdminSuccessStoryListCreateView.as_view(), name='admin-stories-list'),
    path('admin/stories/<int:pk>/', AdminSuccessStoryDetailView.as_view(), name='admin-story-detail'),
    path('admin/plans/<int:pk>/', AdminSubscriptionPlanDetailView.as_view(), name='admin-plan-detail'),
    path('admin/plans/', AdminSubscriptionPlanView.as_view(), name='admin-subscription-plans'),
    path('admin/payments/', AdminPaymentListView.as_view(), name='admin-payments-list'),
    path('payment/admin-details/', AdminPaymentDetailsView.as_view(), name='admin-payment-details'),
    path('payment/process-purchase/', ProcessPlanPurchaseView.as_view(), name='process-purchase'),
    path('payment/create-order/', CreateRazorpayOrderView.as_view(), name='create-order'),
    path('payment/verify/', VerifyPaymentView.as_view(), name='verify-payment'),
    
]