# Generated by Django 5.2.14 on 2026-06-10 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_created_by_admin_profile_is_created_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsettings',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
    ]
