# Generated by Django 5.2.14 on 2026-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_adminsettings_bio_remove_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
