# Generated by Django 5.2.14 on 2026-06-11 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_aadhaarverification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarverification',
            name='aadhaar_image',
            field=models.ImageField(upload_to='aadhaar_verification/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
