# Generated by Django 5.2.14 on 2026-06-11 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_aadhaarverification_aadhaar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aadhaarverification',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_aadhaars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='aadhaar_image',
            field=models.ImageField(upload_to='aadhaar/'),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
