# Generated by Django 5.2.14 on 2026-06-11 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_aadhaarverification_verified_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aadhaarverification',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='aadhaarverification',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aadhaar_verification', to=settings.AUTH_USER_MODEL),
        ),
    ]
