# Generated by Django 5.2.14 on 2026-06-13 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_aadhaarverification_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreferences',
            name='activity_status',
            field=models.CharField(default='Everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='age_preference',
            field=models.CharField(default='All Ages', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='distance',
            field=models.CharField(default='Anywhere', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='show_me',
            field=models.CharField(default='Everyone', max_length=20),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
