# Generated by Django 5.2.14 on 2026-06-17 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_chatroom_unique_together_message_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
