# Generated by Django 5.2.14 on 2026-06-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_adminsettings_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='role',
            field=models.CharField(default='Admin', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
