# Generated by Django 5.2.14 on 2026-06-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_adminsettings_role_alter_adminsettings_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='Success', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('duration_months', models.IntegerField(default=1)),
                ('features', models.TextField(help_text='Comma separated features')),
            ],
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_one', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('image_two', models.ImageField(blank=True, null=True, upload_to='success_stories/')),
                ('partner_one_name', models.CharField(max_length=100)),
                ('partner_two_name', models.CharField(max_length=100)),
                ('marriage_date', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('story_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
