# Generated by Django 5.2.14 on 2026-06-19 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_payment_subscriptionplan_successstory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='State Bank of India', max_length=100)),
                ('account_number', models.CharField(default='1234567890', max_length=50)),
                ('ifsc_code', models.CharField(default='SBIN0001234', max_length=20)),
                ('account_holder', models.CharField(default='Zinda Admin', max_length=100)),
                ('upi_id', models.CharField(default='zinda@upi', max_length=100)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='admin_payment/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='initiated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by',
            field=models.ManyToManyField(blank=True, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
