# Generated by Django 5.2.14 on 2026-06-23 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_message_reply_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat_room',
            new_name='room',
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted_for_everyone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='voice_file',
            field=models.FileField(blank=True, null=True, upload_to='voice/'),
        ),
    ]
