# Generated by Django 5.2.14 on 2026-06-27 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_convert_price_to_int'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminpaymentmethod',
            options={'verbose_name': 'Admin Payment Method', 'verbose_name_plural': 'Admin Payment Methods'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'ordering': ['price']},
        ),
        migrations.RemoveField(
            model_name='adminpaymentmethod',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='adminpaymentmethod',
            name='account_holder',
            field=models.CharField(default='Muhammed Rafi.T', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminpaymentmethod',
            name='account_number',
            field=models.CharField(default='29720110039977', max_length=50),
        ),
        migrations.AlterField(
            model_name='adminpaymentmethod',
            name='bank_name',
            field=models.CharField(default='UCO Bank', max_length=100),
        ),
        migrations.AlterField(
            model_name='adminpaymentmethod',
            name='ifsc_code',
            field=models.CharField(default='UCBA0002972', max_length=20),
        ),
        migrations.AlterField(
            model_name='adminpaymentmethod',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.AlterField(
            model_name='adminpaymentmethod',
            name='upi_id',
            field=models.CharField(default='mrafiajk-1@oksbi', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='card_digits',
            field=models.CharField(blank=True, default='0000', max_length=4),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.subscriptionplan'),
        ),
    ]
