# Generated by Django 5.2.14 on 2026-07-01 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_payment_options_rename_date_payment_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
