# Generated by Django 5.2.14 on 2026-07-14 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_subscriptionplan_is_active_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationSetting',
        ),
    ]
