# Generated by Django 5.2.14 on 2026-07-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_delete_notificationsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adminprofile',
            old_name='profile_picture',
            new_name='profile_image',
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='AdminSettings',
        ),
    ]
